## task01

/**
* Перепишите код, воспользовавшись механизмом try-with-resources
*/


## task02

/*
Создайте метод doSomething(), который может быть источником одного
из типов checked exceptions(тело самого метода прописывать не обязательно).
Вызовите этот метод из main и обработайте в нем исключение, которое вызвал
метод doSomething().
*/


## counter

/**
Создайте класс Счетчик, у которого есть метод add(), увеличивающий значение
внутренней int переменной на 1. Сделайте так, чтобы с объектом такого типа
можно было работать в блоке try-with-resources. Подумайте, что должно происходить
при закрытии этого ресурса? Напишите метод для проверки, закрыт ли ресурс.
При попытке вызвать add() у закрытого ресурса, должен выброситься IOException
*/


## task04

/**
Задание 3.1
Создайте класс исключения, который будет выбрасываться при делении на 0.
Исключение должно отображать понятное для пользователя сообщение об ошибке.
*/

/**
* Задание 3.2
Создайте класс исключений, которое будет возникать при обращении к пустому элементу в массиве ссылочного типа.
Исключение должно отображать понятное для пользователя сообщение об ошибке.
*/

/**
* Задание 3.3
* Создайте класс исключения, которое будет возникать при попытке открыть несуществующий файл.
* Исключение должно отображать понятное для пользователя сообщение об ошибке.
* */

## task05

/**
Создайте класс Счетчик, у которого есть метод add(), увеличивающий значение
внутренней int переменной на 1. Сделайте так, чтобы с объектом такого типа
можно было работать в блоке try-with-resources. Подумайте, что должно происходить
при закрытии этого ресурса? Напишите метод для проверки, закрыт ли ресурс.
При попытке вызвать add() у закрытого ресурса, должен выброситься IOException
*/